In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

In [2]:
test_df = pd.read_csv("eda_dataset_test.csv")
df = pd.read_csv("eda_dataset_train.csv")

In [3]:
X_train = df[['term', 'loan_age', 'emp_length', 'sub_grade_combined', 'int_rate', 'loan_amnt', 'account_bal', 'cibil_score', 'annual_inc']]
y_train = df['loan_status']

X_test = test_df[['term', 'loan_age', 'emp_length', 'sub_grade_combined', 'int_rate', 'loan_amnt', 'account_bal', 'cibil_score', 'annual_inc']]
y_test = test_df['loan_status']

In [16]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [24]:
y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.6663512714370196

In [6]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.60      0.21      0.31      3055\n           1       0.67      0.92      0.78      5400\n\n    accuracy                           0.66      8455\n   macro avg       0.64      0.56      0.54      8455\nweighted avg       0.65      0.66      0.61      8455\n'

In [28]:
log_reg_scores = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')  # cv=5 for 5 folds
np.mean(log_reg_scores)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

0.7534761004353371

In [25]:
confusion_matrix(y_test, y_pred)

array([[ 731, 2324],
       [ 497, 4903]])

In [31]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [33]:
y_pred = rf_model.predict(X_test)

accuracy_score(y_test, y_pred)

0.6713187463039622

In [36]:
cross_val_score(rf_model, X_train, y_train, cv=5, scoring='accuracy')


array([0.73963326, 0.33894728, 0.32034651, 0.41673629, 0.28499186])

In [10]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.61      0.26      0.36      3055\n           1       0.68      0.90      0.78      5400\n\n    accuracy                           0.67      8455\n   macro avg       0.64      0.58      0.57      8455\nweighted avg       0.66      0.67      0.63      8455\n'

In [11]:
confusion_matrix(y_test, y_pred)

array([[ 790, 2265],
       [ 514, 4886]])

In [38]:
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:34:45] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [39]:
 cross_val_score(xgb_model, X_train, y_train, cv=5, scoring='accuracy')

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:34:56] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:34:57] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:34:58] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:35:02] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [18:35:02] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_e

array([0.73928147, 0.47372587, 0.41216305, 0.50991601, 0.2839365 ])

In [13]:
y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.6723832052040213